User/chepel d/for merge
diyruz/AirSense pull request #8
Opened 2021-01-04 13:37 UTC by dmitrychepel

2021-01-07 09:52 UTC, nurikk requested changes

2021-01-07 09:52 UTC, nurikk commented on Source/zcl_app.c
> +    static uint8 temp_sensor_type = 0; // 0 bme280, 1 ds18b20, 2 not found
Can we use something like enum or macros to define me types?

2021-01-07 09:52 UTC, nurikk commented on Source/zcl_app.c
> +        current_co2_sensor_state = 0xff; //a part of algorithm avoiding exceptional io
Kindly don't use magic numbers

2021-01-07 09:52 UTC, nurikk commented on Source/zcl_app.c
>          if (temp == 1) {
Same magic numbers

2021-01-07 20:51 UTC, dmitrychepel commented on Source/zcl_app.c
>          if (temp == 1) {
fixed but "temp==1" leaved.
it was before, and I don't have DS18B20 to check it.
I see that readTemperature is buggy now.
"1" very bad constant for temperature device to indicate mistake of operation.

2021-01-11 23:59 UTC, merged

2021-01-11 23:59 UTC, nurikk commented
Thanks